-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.zoo
(
    id_zoo serial NOT NULL,
    nombre character varying(60) NOT NULL,
    ciudad character varying(60) NOT NULL,
    tamanio numeric(5, 2) NOT NULL,
    presupuesto numeric(5, 2),
    PRIMARY KEY (id_zoo)
);

CREATE TABLE IF NOT EXISTS public.animal
(
    id serial NOT NULL,
    tamanio numeric(2, 2) NOT NULL,
    especie character varying(60) NOT NULL,
    sexo "char" NOT NULL,
    anio numeric(4) NOT NULL,
    pais character varying(60) NOT NULL,
    continente character varying(60) NOT NULL,
    id_zoo integer NOT NULL,
    id_especie integer NOT NULL,
    PRIMARY KEY (id_zoo)
);

CREATE TABLE IF NOT EXISTS public.especie
(
    id_especie serial NOT NULL,
    nombre_cientifico character varying(60) NOT NULL,
    nombre_vulgar character varying(60) NOT NULL,
    familia character varying(60) NOT NULL,
    extincion "char" NOT NULL,
    PRIMARY KEY (id_especie)
);

ALTER TABLE IF EXISTS public.animal
    ADD CONSTRAINT fk_animal_zoo FOREIGN KEY (id_zoo)
    REFERENCES public.zoo (id_zoo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.animal
    ADD CONSTRAINT fk_animal_especie FOREIGN KEY (id_especie)
    REFERENCES public.especie (id_especie) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;