-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


DROP TABLE IF EXISTS public.animal;

CREATE TABLE IF NOT EXISTS public.animal
(
    id_animal integer NOT NULL DEFAULT nextval('seq_animal'::regclass),
    fk_id_zoo integer NOT NULL,
    fk_id_especie integer NOT NULL,
    tamano integer NOT NULL,
    sexo character varying(1) COLLATE pg_catalog."default",
    ano date NOT NULL,
    pais character varying(50) COLLATE pg_catalog."default" NOT NULL,
    continente character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT animal_pkey PRIMARY KEY (id_animal)
);

DROP TABLE IF EXISTS public.especie;

CREATE TABLE IF NOT EXISTS public.especie
(
    id_especie integer NOT NULL DEFAULT nextval('seq_especie'::regclass),
    nombre_cientifico character varying(50) COLLATE pg_catalog."default" NOT NULL,
    nombre_vulgar character varying(50) COLLATE pg_catalog."default" NOT NULL,
    familia character varying(50) COLLATE pg_catalog."default" NOT NULL,
    extincion character varying(2) COLLATE pg_catalog."default",
    CONSTRAINT especie_pkey PRIMARY KEY (id_especie)
);

DROP TABLE IF EXISTS public.zoo;

CREATE TABLE IF NOT EXISTS public.zoo
(
    id_zoo integer NOT NULL DEFAULT nextval('seq_zoo'::regclass),
    nombre character varying(20) COLLATE pg_catalog."default" NOT NULL,
    ciudad character varying(20) COLLATE pg_catalog."default" NOT NULL,
    pais character varying(20) COLLATE pg_catalog."default" NOT NULL,
    tamano integer NOT NULL,
    presupuesto integer NOT NULL,
    CONSTRAINT zoo_pkey PRIMARY KEY (id_zoo)
);

ALTER TABLE IF EXISTS public.animal
    ADD CONSTRAINT animal_fk_id_especie_fkey FOREIGN KEY (fk_id_especie)
    REFERENCES public.especie (id_especie) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.animal
    ADD CONSTRAINT animal_fk_id_zoo_fkey FOREIGN KEY (fk_id_zoo)
    REFERENCES public.zoo (id_zoo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;